### ISSUE TITLE
Update for HCAR 35 (November 2018)

### ISSUE THREAD

**Issue by mihaimaruseac** [HaskellMN/hcar#1]
Hi,

I have sent the CFC for HCAR 35, the November 2018 edition, on Saturday this weekend and now I found this repo. I wanted to notify you here too, in case you want to sent an update. The deadline is on 4th of November 2018.

Thanks.

**Comment by kmarekspartz** [comment]
Thanks!

The current info is incorrect, my name and @tylerholien should be swapped for @trevorriles and someone else.

Additionally, it is now Third Tuesdays in Minneapolis. :)

**Comment by kmarekspartz** [comment]
@mihaimaruseac Is this repo sufficient for you or do you need the file in some other form?

**Comment by mihaimaruseac** [comment]
Usually an email to my email address (same name as github username  at google.com) so I don't forget. But I made a note of this, so should be ok.
